services:
  ktdoctor:
    build:
      context: .
      args:
        NEXT_PUBLIC_BASE_PATH: ${NEXT_PUBLIC_BASE_PATH-/ktdoctor}
    restart: unless-stopped
    ports:
      - "${HOST_PORT:-8160}:3000"
    env_file:
      - .env
